import Head from "next/head";
import Image from "next/image";
import JobContainer from "../components/JobSection";
import styles from "../styles/Home.module.css";
import { Box, Heading, Text } from "@chakra-ui/react";

export default function Home() {
  return (
    <section className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box w="90%" m="auto">
          <Box mt={10} mb={10} bgColor="#1c1c24" borderRadius="10" p={5}>
            <Heading as="h1" size="md">
              Openings
            </Heading>

            <Text fontSize="sm" mt={2}>
              Find what ever jobs suites you the most and never settle for less
            </Text>
          </Box>

          <JobContainer />
        </Box>
      </main>
    </section>
  );
}
